package com.MosIC.MosIC_Office.matpass.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."MATERIAL_PASS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "IN_OR_OUT" CHARACTER VARYING(20) NOT NULL,
    "PARTY" CHARACTER VARYING(100) NOT NULL,
    "DATE" CHARACTER VARYING(100) NOT NULL,
    "CONTACTPERSON" CHARACTER VARYING(100) NOT NULL,
    "DISCRIPTION" CHARACTER VARYING(100) NOT NULL,
    "FILEREF" CHARACTER VARYING(100) NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class MatpassDTO {

    private Long id; // wrapper type allows null
    private String inOrOut;
    private String party;
    private String date;
    private String contactPerson;
    private String discription;
    private String fileRef;
    private Integer status;     // must be Integer to match TINYINT

}
