package com.MosIC.MosIC_Office.purchase.entity;

import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * @author MosIC
 * @date 2024/6/11 17:28
 *
 * CREATE CACHED TABLE "PUBLIC"."PURCHASE_REGISTER"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "P_DATE" CHARACTER VARYING(50) NOT NULL,
    "P_VALIDITY" CHARACTER VARYING(100) NOT NULL,
    "P_FROM_PARTY" CHARACTER VARYING(250) NOT NULL,
    "P_TO_PARTY" CHARACTER VARYING(250) NOT NULL,
    "P_ENQUIRE_DATE" CHARACTER VARYING(100) NOT NULL,
    "P_DELIVERY_TERMS" CHARACTER VARYING(250) NOT NULL,
    "P_PAYMENT_TERMS" CHARACTER VARYING(250) NOT NULL,
    "P_CURRENCY" CHARACTER VARYING(100) NOT NULL,
    "P_DOCTYPE" INTEGER DEFAULT 1 COMMENT '1=RFQ, 2=Quotation, 3=SupplyOrder, 4=Invoice, 5=Payment, 6=PaymentReceipt' NOT NULL,
    "P_TX_TYPE" CHARACTER VARYING(100) NOT NULL,
    "P_DESCRIPTION" CHARACTER VARYING(250) NOT NULL,
    "P_ADDRESSED_TO" CHARACTER VARYING(250) NOT NULL,
    "P_FILEREF" CHARACTER VARYING(100) DEFAULT NULL,
    "STATUS" INTEGER DEFAULT 1 COMMENT '1=available, 0=deleted' NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  );
  *
  */

@Getter
@Setter
@Entity
@AllArgsConstructor
@NoArgsConstructor

@Table(name = "purchase_register")
public class PurchaseEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "p_date")
  private String purchaseDate;

  @Column(name = "p_validity")
  private String purchaseValidity;

  @Column(name = "p_from_party")
  private String purchaseFromParty;

  @Column(name = "p_to_party")
  private String purchaseToParty;

  @Column(name = "p_enquire_date")
  private String purchaseEnquireDate;

  @Column(name = "p_delivery_terms")
  private String purchaseDeliveryTerms;

  @Column(name = "p_payment_terms")
  private String purchasePaymentTerms;

  @Column(name = "p_currency")
  private String purchaseCurrency;

  @Column(name = "p_doctype")
  private Integer purchaseDoctype;

  @Column(name = "p_tx_type")
  private String purchaseTxType;

  @Column(name = "p_description")
  private String purchaseDescription;

  @Column(name = "p_addressed_to")
  private String purchaseAddressedTo;

  @Column(name = "p_fileref")
  private String purchaseFileRef;

  @Column(name = "status")
  private Integer purchaseStatus;

}
