package com.MosIC.MosIC_Office.stocksItem.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * @author MosIC
 * @date 2024/6/11 17:28
 */
/**
 * CREATE CACHED TABLE "PUBLIC"."STOCK_ITEMS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "PRODUCT_NAME" CHARACTER VARYING(255) NOT NULL,
    "OPENING_DATE" CHARACTER VARYING(255) NOT NULL,
    "SM_DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "SM_UNIT" CHARACTER VARYING(255) NOT NULL,
    "SM_OPENING_BALANCE" INTEGER DEFAULT 0 NOT NULL,
    "STATUS" TINYINT DEFAULT 1 COMMENT '0=deleted,1=notdeleted' NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
  */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class StockItemDTO {

  private Long id;
  private String productName;
  private String openingDate;
  private String smDescription;
  private String smUnit;
  private Integer smOpeningBalance;
  private Integer status;

}
