package com.MosIC.MosIC_Office.matpass.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 *CREATE CACHED TABLE "PUBLIC"."MATERIAL_PASS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "IN_OR_OUT" CHARACTER VARYING(20) NOT NULL,
    "PARTY" CHARACTER VARYING(100) NOT NULL,
    "DATE" CHARACTER VARYING(100) NOT NULL,
    "CONTACTPERSON" CHARACTER VARYING(100) NOT NULL,
    "DISCRIPTION" CHARACTER VARYING(100) NOT NULL,
    "FILEREF" CHARACTER VARYING(100) NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "material_pass")
public class MatpassEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @Column(name = "in_or_out")
    private String inOrOut;

    @Column(name = "party")
    private String party;

    @Column(name = "date")
    private String date;

    @Column(name = "contactperson")
    private String contactPerson;

    @Column(name = "discription")
    private String discription;

    @Column(name = "fileref")
    private String fileRef;

    @Column(name = "status")
    private Integer status;

}
