package com.MosIC.MosIC_Office.customers_party.dto;


/***
 * CREATE CACHED TABLE "PUBLIC"."PARTY_DIRECTORY"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CUSTOMER_ID" CHARACTER VARYING(200) NOT NULL,
    "PARTY_NAME" CHARACTER VARYING(100) NOT NULL,
    "PARTY_PHONENO" CHARACTER VARYING(100) NOT NULL,
    "PARTY_EMAIL" CHARACTER VARYING(150) NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */


import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

public class PartyDTO {

  private Long id;

  @JsonProperty("customerId")
  @JsonAlias({"CUSTOMER_ID", "customer_id"})
  private Long customerId;

  @JsonProperty("customerName")
  @JsonAlias({"CUSTOMER_NAME", "CUSTOMERNAME", "customer_name"})
  private String customerName;

  @JsonProperty("partyName")
  @JsonAlias("PARTY_NAME")
  private String partyName;

  @JsonProperty("partyPhoneno")
  @JsonAlias("PARTY_PHONENO")
  private String partyPhoneno;

  @JsonProperty("partyEmail")
  @JsonAlias("PARTY_EMAIL")
  private String partyEmail;

  @JsonProperty("status")
  @JsonAlias("STATUS")
  private String status;


}
