package com.MosIC.MosIC_Office.stocks.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."STOCK_INOUT_LIST"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "STOCK_ITEM_ID" INTEGER NOT NULL,
    "STOCK_DATE" CHARACTER VARYING(255) NOT NULL,
    "STOCK_DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "STOCK_IN_OUT" CHARACTER VARYING(255) NOT NULL,
    "STOCK_QUANTITY" CHARACTER VARYING(255) NOT NULL,
    "STOCK_RETURNORNONRETURN" CHARACTER VARYING(255) NOT NULL,
    "STOCK_PARTY" CHARACTER VARYING(255) NOT NULL,
    "MAT_PASS_ID" INTEGER NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

public class StocksDTO {
    private Long id;
    private Long stockItemId;
    private String stockDate;
    private String stockDescription;
    private String stockInOut;
    private String stockQuantity;
    private String stockReturnOrNonReturn;
    private String stockParty;
    private Long matPassId;
    private Integer status;


}
