package com.MosIC.MosIC_Office.purchase_items.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."PURCHASE_DOCUMENT_ITEM_LIST"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME_OF_PRODUCT_SERVICE" CHARACTER VARYING(255) DEFAULT NULL,
    "HSN_ACS" CHARACTER VARYING(255) DEFAULT NULL,
    "QUANTITY" INTEGER DEFAULT NULL,
    "UNIT" CHARACTER VARYING(255) DEFAULT NULL,
    "UNITRATE" DECIMAL(10, 2) DEFAULT NULL,
    "TAXABLEVALUE" DECIMAL(10, 2) DEFAULT NULL,
    "CGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "CGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "SGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "SGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "IGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "IGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "TOTAL" DECIMAL(10, 2) DEFAULT NULL,
    "REF_FILE_NO" INTEGER DEFAULT NULL,
    "STATUS" INTEGER DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class PurchaseItemDTO {
    private Long id;
    private String nameOfProductService;
    private String hsnAcs;
    private Integer quantity;
    private String unit;
    private Double unitRate;
    private Double taxableValue;
    private Double cgstRate;
    private Double cgstAmount;
    private Double sgstRate;
    private Double sgstAmount;
    private Double igstRate;
    private Double igstAmount;
    private Double total;
    private Integer refFileNo;
    private Integer status;



}
