package com.MosIC.MosIC_Office.employee_payslip.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/***
 * CREATE CACHED TABLE "PUBLIC"."EMP_PAYSLIP"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "EMP_ID" INTEGER NOT NULL,
    "EMP_MONTH" CHARACTER VARYING(255) NOT NULL,
    "EMP_YEAR" CHARACTER VARYING(255) NOT NULL,
    "BASIC" CHARACTER VARYING(255) NOT NULL,
    "HRA" CHARACTER VARYING(255) NOT NULL,
    "ALLOWANCESS" CHARACTER VARYING(255) NOT NULL,
    "TOTAL_GROSS" CHARACTER VARYING(255) NOT NULL,
    "TDS" CHARACTER VARYING(255) NOT NULL,
    "PT" CHARACTER VARYING(255) NOT NULL,
    "LOAN" CHARACTER VARYING(255) NOT NULL,
    "TOTAL_DEDUCTION" CHARACTER VARYING(255) NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class EmpPayslipDTO {
    private Long id;                // long wrapper, allows null
    private Long empId;             // Employee ID (foreign key reference)
    private String empMonth;        // Month of payslip
    private String empYear;         // Year of payslip
    private String basic;           // Basic salary
    private String hra;             // House Rent Allowance
    private String allowancess;     // Other allowances
    private String totalGross;      // Total gross salary
    private String tds;             // Tax Deducted at Source
    private String pt;              // Professional Tax
    private String loan;            // Loan deduction
    private String totalDeduction;  // Total deductions
    private Integer status;         // Status: 1 (active), 0 (inactive) - CHANGED FROM STRING TO INTEGER
}
