package com.MosIC.MosIC_Office.employee_position.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."EMP_POSITION_TABLE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "EMP_ID" INTEGER NOT NULL,
    "EP_DATE" CHARACTER VARYING(50),
    "EP_EFFICIENT_DATE" CHARACTER VARYING(50),
    "POSITION" CHARACTER VARYING(50),
    "DEPARTMENT" CHARACTER VARYING(50),
    "ROLE" CHARACTER VARYING(50),
    "REPORTING_TO" CHARACTER VARYING(50),
    "EMP_BASIC" DECIMAL(10, 2),
    "EMP_HRA" DECIMAL(10, 2),
    "EMP_ALLOWANCE" DECIMAL(10, 2),
    "EMP_MONTH_GROSS" DECIMAL(10, 2),
    "EMP_CTC" DECIMAL(10, 2),
    "EMP_TDS" DECIMAL(10, 2),
    "EMP_PT" DECIMAL(10, 2),
    "EMP_LOANS" DECIMAL(10, 2),
    "ACTIVE_STATUS" TINYINT DEFAULT 1 NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class EmpPositionDTO {
    private Long id;// long wrapper, allows null
    private Long empId;
    private String epDate;
    private String epEfficientDate;
    private String position;
    private String department;
    private String role;
    private String reportingTo;
    private Double empBasic;
    private Double empHra;
    private Double empAllowance;
    private Double empMonthGross;
    private Double empCtc;
    private Double empTds;
    private Double empPt;
    private Double empLoans;
    private String activeStatus;
    private String status;
}
