package com.MosIC.MosIC_Office.employee.entity;
/**
 * CREATE CACHED TABLE "PUBLIC"."EMPLOYEE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "EMP_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_LAST_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_DOB" CHARACTER VARYING(255) NOT NULL,
    "EMP_PH" CHARACTER VARYING(255) NOT NULL,
    "EMP_MAIL" CHARACTER VARYING(255) NOT NULL,
    "EMP_PAN" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADHAR" CHARACTER VARYING(255) NOT NULL,
    "EMP_ACC_NO" CHARACTER VARYING(244) NOT NULL,
    "EMP_BANK_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_ACC_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_IFSC_CODE" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_1" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_2" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_3" CHARACTER VARYING(255) NOT NULL,
    "EMP_DOJ" CHARACTER VARYING(255),
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */
import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "employee")
public class EmpEntity {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "emp_name")
  private String empName;

  @Column(name = "emp_last_name")
  private String empLastName;
  @Column(name = "emp_dob")
  private String empDob;
  @Column(name = "emp_ph")
  private String empPh;
  @Column(name = "emp_mail")
  private String empMail;
  @Column(name = "emp_pan")
  private String empPan;
  @Column(name = "emp_adhar")
  private String empAdhar;
  @Column(name = "emp_acc_no")
  private String empAccNo;
  @Column(name = "emp_bank_name")
  private String empBankName;
  @Column(name = "emp_acc_name")
  private String empAccName;
  @Column(name = "emp_ifsc_code")
  private String empIfscCode;
  @Column(name = "emp_address_1")
  private String empAddress1;
  @Column(name = "emp_address_2")
  private String empAddress2;
  @Column(name = "emp_address_3")
  private String empAddress3;
  @Column(name = "emp_doj")
  private String empDoj;
  @Column(name = "status")
  private String Status;
}
