package com.MosIC.MosIC_Office.stocksItem.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."STOCK_ITEMS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "PRODUCT_NAME" CHARACTER VARYING(255) NOT NULL,
    "OPENING_DATE" CHARACTER VARYING(255) NOT NULL,
    "SM_DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "SM_UNIT" CHARACTER VARYING(255) NOT NULL,
    "SM_OPENING_BALANCE" INTEGER DEFAULT 0 NOT NULL,
    "STATUS" TINYINT DEFAULT 1 COMMENT '0=deleted,1=notdeleted' NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "stock_items")
public class StockItemEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "product_name")
    private String productName;
    @Column(name = "opening_date")
    private String openingDate;
    @Column(name = "sm_description")
    private String smDescription;
    @Column(name = "sm_unit")
    private String smUnit;
    @Column(name = "sm_opening_balance")
    private Integer smOpeningBalance;
    @Column(name = "status")
    private Integer status;
}
