package com.MosIC.MosIC_Office.customers_party.entity;

/**
 * PartyEntity represents the party entity in the system.
 * CREATE CACHED TABLE "PUBLIC"."PARTY_DIRECTORY"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CUSTOMER_ID" CHARACTER VARYING(200) NOT NULL,
    "PARTY_NAME" CHARACTER VARYING(100) NOT NULL,
    "PARTY_PHONENO" CHARACTER VARYING(100) NOT NULL,
    "PARTY_EMAIL" CHARACTER VARYING(150) NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;

import com.MosIC.MosIC_Office.customers.entity.CustomerEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "party_directory")
public class PartyEntity {


  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  //@Column(name = "customer_id", nullable = false)
  //private String customerId;
  // ── Relationship ───────────────────────────────────────────────────────────
  // Many Party contacts belong to One Customer (company/org)
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "customer_id", nullable = false)
  private CustomerEntity customer;

  @Column(name = "party_name", nullable = false)
  private String partyName;

  @Column(name = "party_phoneno", nullable = false)
  private String partyPhoneno;

  @Column(name = "party_email", nullable = false)
  private String partyEmail;

  @Column(name = "status", nullable = false)
  private String status;
}
