spring.application.name=MosIC_Office

# ===============================
# POSTGRESQL DATABASE CONFIG
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8608jrrjlhs73acjo70-a.virginia-postgres.render.com/mosics_office
spring.datasource.username=mosics_office_user
spring.datasource.password=LRFpHZjccxuVtbwsMb0uIo2hSFuDACuK

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# ===============================
# FILE UPLOAD SIZE LIMITS
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=MosIC_Office_Secret_Key_2026_XXXX_SuperLongAndSecure