package com.MosIC.MosIC_Office.stocks.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."STOCK_INOUT_LIST"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "STOCK_ITEM_ID" INTEGER NOT NULL,
    "STOCK_DATE" CHARACTER VARYING(255) NOT NULL,
    "STOCK_DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "STOCK_IN_OUT" CHARACTER VARYING(255) NOT NULL,
    "STOCK_QUANTITY" CHARACTER VARYING(255) NOT NULL,
    "STOCK_RETURNORNONRETURN" CHARACTER VARYING(255) NOT NULL,
    "STOCK_PARTY" CHARACTER VARYING(255) NOT NULL,
    "MAT_PASS_ID" INTEGER NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "stock_inout_list")
public class StocksEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "stock_item_id")
    private Long stockItemId;
    @Column(name = "stock_date")
    private String stockDate;
    @Column(name = "stock_description")
    private String stockDescription;
    @Column(name = "stock_in_out")
    private String stockInOut;
    @Column(name = "stock_quantity")
    private String stockQuantity;
    @Column(name = "stock_returnornonreturn")
    private String stockReturnOrNonReturn;
    @Column(name = "stock_party")
    private String stockParty;
    @Column(name = "mat_pass_id")
    private Long matPassId;
    @Column(name = "status")
    private Integer status;

}
