package com.MosIC.MosIC_Office.purchase_items.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."PURCHASE_DOCUMENT_ITEM_LIST"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "NAME_OF_PRODUCT_SERVICE" CHARACTER VARYING(255) DEFAULT NULL,
    "HSN_ACS" CHARACTER VARYING(255) DEFAULT NULL,
    "QUANTITY" INTEGER DEFAULT NULL,
    "UNIT" CHARACTER VARYING(255) DEFAULT NULL,
    "UNITRATE" DECIMAL(10, 2) DEFAULT NULL,
    "TAXABLEVALUE" DECIMAL(10, 2) DEFAULT NULL,
    "CGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "CGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "SGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "SGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "IGST_RATE" DECIMAL(10, 2) DEFAULT NULL,
    "IGST_AMOUNT" DECIMAL(10, 2) DEFAULT NULL,
    "TOTAL" DECIMAL(10, 2) DEFAULT NULL,
    "REF_FILE_NO" INTEGER DEFAULT NULL,
    "STATUS" INTEGER DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "purchase_document_item_list")
public class PurchaseItemEntity {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "name_of_product_service")
  private String nameOfProductService;

  @Column(name = "hsn_acs")
  private String hsnAcs;

  @Column(name = "quantity")
  private Integer quantity;

  @Column(name = "unit")
  private String unit;

  @Column(name = "unitrate")
  private Double unitRate;

  @Column(name = "taxablevalue")
  private Double taxableValue;

  @Column(name = "cgst_rate")
  private Double cgstRate;

  @Column(name = "cgst_amount")
  private Double cgstAmount;

  @Column(name = "sgst_rate")
  private Double sgstRate;

  @Column(name = "sgst_amount")
  private Double sgstAmount;

  @Column(name = "igst_rate")
  private Double igstRate;

  @Column(name = "igst_amount")
  private Double igstAmount;

  @Column(name = "total")
  private Double total;

  @Column(name = "ref_file_no")
  private Integer refFileNo;

  @Column(name = "status")
  private Integer status;


}
