package com.MosIC.MosIC_Office.employee_position.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."EMP_POSITION_TABLE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "EMP_ID" INTEGER NOT NULL,
    "EP_DATE" CHARACTER VARYING(50),
    "EP_EFFICIENT_DATE" CHARACTER VARYING(50),
    "POSITION" CHARACTER VARYING(50),
    "DEPARTMENT" CHARACTER VARYING(50),
    "ROLE" CHARACTER VARYING(50),
    "REPORTING_TO" CHARACTER VARYING(50),
    "EMP_BASIC" DECIMAL(10, 2),
    "EMP_HRA" DECIMAL(10, 2),
    "EMP_ALLOWANCE" DECIMAL(10, 2),
    "EMP_MONTH_GROSS" DECIMAL(10, 2),
    "EMP_CTC" DECIMAL(10, 2),
    "EMP_TDS" DECIMAL(10, 2),
    "EMP_PT" DECIMAL(10, 2),
    "EMP_LOANS" DECIMAL(10, 2),
    "ACTIVE_STATUS" TINYINT DEFAULT 1 NOT NULL,
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Entity
@Table(name = "emp_position_table")
public class EmpPositionEntity {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "emp_id")
  private Long empId;
  @Column(name = "ep_date")
  private String epDate;
  @Column(name = "ep_efficient_date")
  private String epEfficientDate;
  @Column(name = "position")
  private String position;
  @Column(name = "department")
  private String department;
  @Column(name = "role")
  private String role;
  @Column(name = "reporting_to")
  private String reportingTo;
  @Column(name = "emp_basic")
  private Double empBasic;
  @Column(name = "emp_hra")
  private Double empHra;
  @Column(name = "emp_allowance")
  private Double empAllowance;
  @Column(name = "emp_month_gross")
  private Double empMonthGross;
  @Column(name = "emp_ctc")
  private Double empCtc;
  @Column(name = "emp_tds")
  private Double empTds;
  @Column(name = "emp_pt")
  private Double empPt;
  @Column(name = "emp_loans")
  private Double empLoans;
  @Column(name = "active_status")
  private Integer activeStatus;
  @Column(name = "status")
  private Integer status;
}
