package com.MosIC.MosIC_Office.sales.entity;


import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

/*
  CREATE CACHED TABLE "PUBLIC"."SALES_REGISTER"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "S_DATE" CHARACTER VARYING(50) NOT NULL,
    "S_VALIDITY" CHARACTER VARYING(100) NOT NULL,
    "S_FROM_PARTY" CHARACTER VARYING(250) NOT NULL,
    "S_TO_PARTY" CHARACTER VARYING(250) NOT NULL,
    "S_ENQUIRE_DATE" CHARACTER VARYING(100) NOT NULL,
    "S_DELIVERY_TERMS" CHARACTER VARYING(250) NOT NULL,
    "S_PAYMENT_TERMS" CHARACTER VARYING(250) NOT NULL,
    "S_CURRENCY" CHARACTER VARYING(100) NOT NULL,
    "S_DOCTYPE" TINYINT DEFAULT 1 COMMENT '1=RFQ, 2=Quotation, 3=SupplyOrder, 4=Invoice, 5=Payment, 6=PaymentReceipt' NOT NULL,
    "S_TX_TYPE" CHARACTER VARYING(100) NOT NULL,
    "S_DESCRIPTION" CHARACTER VARYING(250) NOT NULL,
    "S_ADDRESSED_TO" CHARACTER VARYING(250) NOT NULL,
    "S_FILEREF" CHARACTER VARYING(100) DEFAULT NULL,
    "STATUS" TINYINT DEFAULT 1 COMMENT '1=available, 0=deleted' NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
  );

*/
@Entity
@Table(name = "sales_register")
public class SalesEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "s_date")
    private String salesDate;

    @Column(name = "s_validity")
    private String salesValidity;

    @Column(name = "s_from_party")
    private String salesFromParty;

    @Column(name = "s_to_party")
    private String salesToParty;

    @Column(name = "s_enquire_date")
    private String salesEnquireDate;

    @Column(name = "s_delivery_terms")
    private String salesDeliveryTerms;

    @Column(name = "s_payment_terms")
    private String salesPaymentTerms;

    @Column(name = "s_currency")
    private String salesCurrency;

    @Column(name = "s_doctype")
    private String salesDoctype;

    @Column(name = "s_tx_type")
    private String salesTxType;

    @Column(name = "s_description")
    private String salesDescription;

    @Column(name = "s_addressed_to")
    private String salesAddressedTo;

    @Column(name = "s_fileref")
    private String salesFileRef;

    @Column(name = "status")
    private String salesStatus;


}
