package com.MosIC.MosIC_Office.employee.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CREATE CACHED TABLE "PUBLIC"."EMPLOYEE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "EMP_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_LAST_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_DOB" CHARACTER VARYING(255) NOT NULL,
    "EMP_PH" CHARACTER VARYING(255) NOT NULL,
    "EMP_MAIL" CHARACTER VARYING(255) NOT NULL,
    "EMP_PAN" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADHAR" CHARACTER VARYING(255) NOT NULL,
    "EMP_ACC_NO" CHARACTER VARYING(244) NOT NULL,
    "EMP_BANK_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_ACC_NAME" CHARACTER VARYING(255) NOT NULL,
    "EMP_IFSC_CODE" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_1" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_2" CHARACTER VARYING(255) NOT NULL,
    "EMP_ADDRESS_3" CHARACTER VARYING(255) NOT NULL,
    "EMP_DOJ" CHARACTER VARYING(255),
    "STATUS" TINYINT DEFAULT 1 NOT NULL,
    "DATECREATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class EmpDTO {

  private Long id;// long wrapper, allows null
  private String empName;
  private String empLastName;
  private String empDob;
  private String empPh;
  private String empMail;
  private String empPan;
  private String empAdhar;
  private String empAccNo;
  private String empBankName;
  private String empAccName;
  private String empIfscCode;
  private String empAddress1;
  private String empAddress2;
  private String empAddress3;
  private String empDoj;
  private String status;

}
